//NOMBRE

//CLAVE

// EJERCICIO:

//CATEDRÁTICO:


// UN ALUMNO DESEA SABER 	CUÁL SERA SU PROMEDIO GENERLA
//EN LAS TRES MATERIAS MÁS DIFICILES QUE CURSA
//Y CUAL SERÁ EL PROMEDIO QUE OBTENDRÁ EN CADA UNA DE ELLAS
//eSTAS MATERIAS SE EVALUAN COMO SE MUESTRA A CONTINUACIÓN


