//NOMBRES

//CLAVE :

//EJERCICIO:

//CATEDRÁTICO : CHRISTIAN FERNANDO SAPÓN PÉREZ

//UN VENDEDOR DESEA SABER CUANTO RECIBIRÁ EN EL MES

//EL VENDEDOR RECIBE UN SUELDO BASE MÁS UN 10% DE LAS VENTAS QUE REALICE EN EL MES
//SE DESEA SABER CUANTO DINERO OBTENDRA POR CONCEPTO DE COMISIONES POR LAS }
// 3 VENTAS QUE REALIZA EN EL MES
// Y EL TOTAL QUE RECIBIRÁ EN EL MES TOMANDO EN CUENTA SU SUELDO BASE Y COMISIONES
